---
- name: "p2"
  
  stream:
    action_count: 0
    enabled: true
    flags: 3
    flow_stats:
      enabled: true
      rule_type: "stats"
      stream_id: 2
    isg: 0.0
    mode:
      rate:
        type: "percentage"
        value: 64.0
      type: "continuous"
      total_pkts: 1
      pkts_per_burst: 1
      ibg: 0.0
      count: 1
    
    packet:
      binary: "AAMAAAADAgAAAAACCABFAADuBNIAAH8AFzpnAAAAIAAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna"
      meta: "eyJwcm90b2NvbF9zZWxlY3Rpb24iOnsiaXNfdGNwX3NlbGVjdGVkIjpmYWxzZSwibWluX2xlbmd0aCI6IjY0IiwiaXNfaXB2NF9zZWxlY3RlZCI6dHJ1ZSwiaXNfdWRwX3NlbGVjdGVkIjpmYWxzZSwibWF4X2xlbmd0aCI6IjE1MTgiLCJmcmFtZV9sZW5ndGgiOiIyNTYiLCJpc19wYXR0ZXJuX3NlbGVjdGVkIjp0cnVlLCJmcmFtZV9sZW5ndGhfdHlwZSI6IkZpeGVkIiwiaXNfdGFnZ2VkX3ZsYW5fc2VsZWN0ZWQiOmZhbHNlfSwiZXRoZXJuZXQiOnsidHlwZSI6IjA4MDAiLCJpc19vdmVycmlkZSI6dHJ1ZX0sIm1hYyI6eyJzb3VyY2UiOnsic3RlcCI6IjEiLCJhZGRyZXNzIjoiMDI6MDA6MDA6MDA6MDA6MDIiLCJjb3VudCI6IjkwMDAiLCJtb2RlIjoiRml4ZWQifSwiZGVzdGluYXRpb24iOnsic3RlcCI6IjEiLCJhZGRyZXNzIjoiMDA6MDM6MDA6MDA6MDA6MDMiLCJjb3VudCI6IjkwMDAiLCJtb2RlIjoiRml4ZWQifX0sImlwdjQiOnsic291cmNlIjp7InN0ZXAiOiIxIiwiYWRkcmVzcyI6IjEwMy4wLjAuMCIsImNvdW50IjoiNTAwMDAwIiwibW9kZSI6IkluY3JlbWVudCBIb3N0In0sImRlc3RpbmF0aW9uIjp7InN0ZXAiOiIxIiwiYWRkcmVzcyI6IjMyLjAuMC4wIiwiY291bnQiOiI1MDAwMDAiLCJtb2RlIjoiSW5jcmVtZW50IEhvc3QifX0sInRjcCI6eyJpc19vdmVycmlkZV9kc3RfcG9ydCI6ZmFsc2UsImNoZWNrc3VtIjoiQjNFMyIsImlzX292ZXJyaWRlX3NyY19wb3J0IjpmYWxzZSwiaXNfb3ZlcnJpZGVfY2hlY2tzdW0iOmZhbHNlLCJkc3RfcG9ydCI6IjEwMjUiLCJzcmNfcG9ydCI6IjEwMjUiLCJpc19zeW5jIjpmYWxzZSwidXJnZW50X3BvaW50ZXIiOiIwIiwiYWNrX251bWJlciI6IjAiLCJpc191cmciOmZhbHNlLCJpc19hY2siOmZhbHNlLCJpc19yc3QiOmZhbHNlLCJpc19maW4iOmZhbHNlLCJpc19wc2giOmZhbHNlLCJ3aW5kb3ciOiIxMDI0Iiwic2VxdWVuY2VfbnVtYmVyIjoiMTI5MDE4In0sInVkcCI6eyJpc19vdmVycmlkZV9kc3RfcG9ydCI6ZmFsc2UsImNoZWNrc3VtIjoiRkZCQSIsImlzX292ZXJyaWRlX3NyY19wb3J0IjpmYWxzZSwiaXNfb3ZlcnJpZGVfbGVuZ3RoIjpmYWxzZSwiaXNfb3ZlcnJpZGVfY2hlY2tzdW0iOmZhbHNlLCJkc3RfcG9ydCI6IjEwMjUiLCJzcmNfcG9ydCI6IjEwMjUiLCJsZW5ndGgiOiIyNiJ9LCJwYXlsb2FkIjp7InBhdHRlcm4iOiIwMCIsInR5cGUiOiJJbmNyZW1lbnQgQnl0ZSJ9LCJ2bGFuIjp7InRwX2lkIjoiRkZGRiIsInZfaWQiOiIwIiwiaXNfb3ZlcnJpZGVfdHBfaWQiOmZhbHNlLCJjZmkiOiIwIiwicHJpb3JpdHkiOiIwIn0sImFkdmFuc2VkX3Byb3BlcnRpZXMiOnsiY2FjaGVfdmFsdWUiOiI1MDAwIiwiY2FjaGVfc2l6ZV90eXBlIjoiQXV0byJ9LCJtb2RlbF92ZXJzaW9uIjoiMS4wIn0="
      model: ""
    self_start: true
    start_paused: false
    advanced_mode: false
    vm:
      split_by_var: "ip_src"
      instructions:
      - init_value: "48.0.0.1"
        min_value: "48.0.0.1"
        max_value: "48.255.255.254"
        name: "ip_dest"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_dest"
        pkt_offset: 30
        type: "write_flow_var"
      - init_value: "102.0.0.1"
        min_value: "102.0.0.1"
        max_value: "102.255.255.254"
        name: "ip_src"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_src"
        pkt_offset: 26
        type: "write_flow_var"
      - pkt_offset: 14
        type: "fix_checksum_ipv4"
      cache_size: 5000
  stream_id: 0
