rmmod joydev
rmmod mei_me
rmmod mei
rmmod lp
rmmod parport
rmmod ip6table_filter 
rmmod iptable_filter  
rmmod ip6_tables
rmmod ip_tables
rmmod ebtable_nat
rmmod ebtables    
rmmod x86_pkg_temp_thermal 
rmmod intel_powerclamp   
rmmod coretemp 
rmmod x86_pkg_temp_thermal 
rmmod intel_powerclamp 
rmmod coretemp
rmmod crct10dif_pclmul
rmmod crc32_pclmul  
rmmod shpchp 
rmmod wmi                  
rmmod acpi_power_meter    
rmmod 8250_fintek   
rmmod lpc_ich          
rmmod mac_hid      
rmmod iTCO_wdt                
rmmod iTCO_vendor_support    
rmmod mfd_core                
rmmod ipmi_si                 
rmmod ipmi_msghandler        
rmmod i2c_i801                
rmmod tpm_tis                 
rmmod tpm                    

rmmod cfg80211         
rmmod rfkill            
rmmod mxm_wmi              
rmmod intel_rapl          
rmmod iosf_mbi           
rmmod vxlan 
rmmod ip6_udp_tunnel   
rmmod ghash_clmulni_intel
rmmod udp_tunnel            
rmmod sb_edac                
rmmod ipmi_ssif             
rmmod edac_core             
rmmod ipmi_msghandler        
rmmod acpi_pad             
rmmod acpi_cpufreq          
rmmod wmi                   
rmmod uas                 
rmmod ast                   

rmmod ufs 
rmmod qnx4
rmmod hfsplus
rmmod hfs
rmmod minix
rmmod ntfs
rmmod mdsos
rmmod jfs
rmmod xfs
rmmod ebtable_filter 
rmmod ebtables 
rmmod ip6table_filter
rmmod ip6_tables
rmmod x86_pkg_temp_thermal
rmmod coretemp
rmmod joydev
rmmod input_leds
rmmod ipmi_ssif
rmmod snd_hda_intel
rmmod shpchp 
rmmod ipmi_si 
rmmod ipmi_msghandler
rmmod 8250_fintek
rmmod tpm_crb
rmmod nfit
rmmod acpi_power_meter
rmmod acpi_pad
rmmod mac_hid  
rmmod ib_iser  
rmmod iscsi_tcp 
rmmod libiscsi_tcp 
rmmod libiscsi
rmmod scsi_transport_iscsi
rmmod btrfs 
rmmod raid10
rmmod raid456
rmmod async_raid6_recov
rmmod async_memcpy
rmmod async_pq
rmmod async_xor
rmmod async_tx
rmmod xor
rmmod raid6_pq
rmmod libcrc32c
rmmod raid0
rmmod raid1
rmmod multipath
rmmod linear
rmmod crct10dif_pclmul
rmmod crc32_pclmul 
rmmod aesni_intel
rmmod lrw
rmmod ablk_helper
rmmod uas
rmmod wmi
rmmod fjes
rmmod rdma_cm
rmmod iw_cm
rmmod ib_cm
rmmod ib_sa
rmmod ib_mad
rmmod ib_core
rmmod ib_addr
rmmod aes_x86_64
rmmod gf128mul
rmmod glue_helper
rmmod cryptd 
rmmod iptable_filter
rmmod ip6table_filter
rmmod ip6_tables
rmmod ip_tables
rmmod x_tables
rmmod usb_storage
rmmod msdos
rmmod btrfs               
rmmod xor                    
rmmod raid6_pq              
rmmod ufs                    
rmmod qnx4                  
rmmod hfsplus              
rmmod hfs                   
rmmod minix                  
rmmod ntfs                  
rmmod jfs                  
rmmod xfs                   
rmmod libcrc32c              
rmmod scsi_transport_iscsi i2c_algo_bit ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops drm
rmmod snd_hda_codec_realtek snd_hda_codec_generic  i915_bpo  intel_ips  snd_hda_codec snd_hda_core snd_hwdep snd_pcm snd_timer  snd  soundcore
rmmod video drm_kms_helper drm i2c_algo_bit fb_sys_fops syscopyarea sysfillrect sysimgblt scsi_transport_iscsi
rmmod crypto_simd cryptd intel_cstate intel_spi_pci intel_spi switchtec
rmmod ipmi_devintf ipmi_msghandler
